web:
    build: .
    ports:
        - "WEB_PORT:8080"
    volumes:
        - ../:/var/www/site
    links:
        - mysql
        - memcached
    expose:
        - "WEB_PORT"
    environment:
        APP_WP_DB_NAME: DATABASE_NAME
        APP_WP_DB_USER: root
        APP_WP_DB_PASS: 1234
        APP_WP_DB_PASSWORD: 1234
        APP_WP_DB_HOST: DATABASE_HOST:DATABASE_PORT
        DL_DB_NAME: DATABASE_NAME
        DL_DB_USER: root
        DL_DB_PASS: 1234
        DL_DB_HOST: DATABASE_HOST
        DL_DB_PORT: DATABASE_PORT
mysql:
    image: mysql
    ports:
        - "MYSQL_PORT:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 1234
    volumes:
        - ./data/dumps:/docker-entrypoint-initdb.d
        - ./data/custom:/etc/mysql/conf.d

memcached:
  image: memcached
  ports:
    - "MEMCACHED_PORT:11211"
