version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: DOCKERFILE
        ports:
            - "WEB_PORT:80"
            - "433"
            - "6001"
        volumes:
            - ../:/var/www/site
        links:
            - mysql
            - memcached
            - redis
        expose:
            - "80"
            - "433"
            - "6001"
        networks:
            - dlocal-net
        depends_on:
            - mysql
            - memcached
            - redis
        environment:
            - REDIS_URL=redis://cache
    mysql:
        image: DB_IMAGE
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "MYSQL_PORT:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        volumes:
            - ./data/dumps:/docker-entrypoint-initdb.d
            - ./data/custom:/etc/mysql/conf.d
            - mysql-data-WEB_PORT:/var/lib/mysql
        networks:
            - dlocal-net
    memcached:
        image: memcached
        restart: always
        ports:
            - "MEMCACHED_PORT:11211"
        networks:
            - dlocal-net
    redis:
        image: redis
        restart: always
        ports:
            - "REDIS_PORT:6379"
        networks:
            - dlocal-net
volumes:
    mysql-data-WEB_PORT:

networks:
    dlocal-net:
        driver: bridge
