#!/bin/bash

H=$(sed -e 's#.*\-h=\([^\-]*\).*#\1#' <<< "$1$2$3$4$5$6$7")

if [ "$H" == "$1$2$3$4$5$6$7" ]; then
    printf "Need to specify a service to ssh into: mysql, web, memcached. Eg. -h=web\n"
    exit 1
fi

./site-up "$1$2$3$4$5$6$7"
